CV_DNN_BACKEND_INFERENCE_ENGINE_NGRAPH = "NGRAPH"
CV_DNN_BACKEND_INFERENCE_ENGINE_NN_BUILDER_API = "NN_BUILDER"
CV_DNN_INFERENCE_ENGINE_CPU_TYPE_ARM_COMPUTE = "ARM_COMPUTE"
CV_DNN_INFERENCE_ENGINE_CPU_TYPE_X86 = "X86"
CV_DNN_INFERENCE_ENGINE_VPU_TYPE_MYRIAD_2 = "Myriad2"
CV_DNN_INFERENCE_ENGINE_VPU_TYPE_MYRIAD_X = "MyriadX"
CV_DNN_INFERENCE_ENGINE_VPU_TYPE_UNSPECIFIED = ""
DNN_BACKEND_CANN = 8
DNN_BACKEND_CUDA = 5
# DNN_BACKEND_DEFAULT equals to DNN_BACKEND_INFERENCE_ENGINE if
# OpenCV is built with Intel OpenVINO or
# DNN_BACKEND_OPENCV otherwise.
DNN_BACKEND_DEFAULT = 0
# DNN_BACKEND_DEFAULT equals to DNN_BACKEND_INFERENCE_ENGINE if
# OpenCV is built with Intel OpenVINO or
# DNN_BACKEND_OPENCV otherwise.
DNN_BACKEND_HALIDE = 1
# Intel OpenVINO computational backend
#
# Note: Tutorial how to build OpenCV with OpenVINO: @ref tutorial_dnn_openvino
DNN_BACKEND_INFERENCE_ENGINE = 2
DNN_BACKEND_OPENCV = 3
DNN_BACKEND_TIMVX = 7
DNN_BACKEND_VKCOM = 4
DNN_BACKEND_WEBNN = 6
DNN_TARGET_CPU = 0
DNN_TARGET_CUDA = 6
DNN_TARGET_CUDA_FP16 = 7
# FPGA device with CPU fallbacks using Inference Engine's Heterogeneous plugin.
DNN_TARGET_FPGA = 5
DNN_TARGET_HDDL = 8
DNN_TARGET_MYRIAD = 3
DNN_TARGET_NPU = 9
DNN_TARGET_OPENCL = 1
DNN_TARGET_OPENCL_FP16 = 2
DNN_TARGET_VULKAN = 4
OPENCV_DNN_API_VERSION = 20221220
SoftNMSMethod_SOFTNMS_GAUSSIAN = 2
SoftNMSMethod_SOFTNMS_LINEAR = 1
